# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      build:
        working_directory: ~/cci-runner
        docker: # run the steps with Docker
          - image: circleci/clojure:lein-2.9.1
        steps: # commands that comprise the `build` job
          - checkout
          - restore_cache: # restores saved cache if checksum hasn't changed since the last run
            key: cci-ms-runner-{{ checksum "project.clj" }}
          - run: lein deps
          - save_cache: # generate and store cache in the .m2 directory using a key template
              paths:
              - ~/.m2
              key: cci-ms-runner-{{ checksum "project.clj" }}
          - run: lein do test, uberjar

    